// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjJwGiZefuz2UI4LEVN7O_aZPYoXr33Fc',
    appId: '1:215428045344:web:e629c538b697527f81fa45',
    messagingSenderId: '215428045344',
    projectId: 'fireside-chat-5df62',
    authDomain: 'fireside-chat-5df62.firebaseapp.com',
    databaseURL: 'https://fireside-chat-5df62-default-rtdb.firebaseio.com',
    storageBucket: 'fireside-chat-5df62.appspot.com',
    measurementId: 'G-P2YZ1N0S93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDFmWnEh0GikzMMzS210eNJ5Rpm-plvH4',
    appId: '1:215428045344:android:13aa9572c178d5f581fa45',
    messagingSenderId: '215428045344',
    projectId: 'fireside-chat-5df62',
    databaseURL: 'https://fireside-chat-5df62-default-rtdb.firebaseio.com',
    storageBucket: 'fireside-chat-5df62.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfNqUOhRDgDA-ZmFdKiFgiM45IuzBLgI0',
    appId: '1:215428045344:ios:31fc2f2baafcaccd81fa45',
    messagingSenderId: '215428045344',
    projectId: 'fireside-chat-5df62',
    databaseURL: 'https://fireside-chat-5df62-default-rtdb.firebaseio.com',
    storageBucket: 'fireside-chat-5df62.appspot.com',
    androidClientId: '215428045344-gqc1rhd6utdljt14i1lh959vre2bs4i5.apps.googleusercontent.com',
    iosClientId: '215428045344-trqkd28mokn42kmmvk4um4avgkp16til.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniexpense',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfNqUOhRDgDA-ZmFdKiFgiM45IuzBLgI0',
    appId: '1:215428045344:ios:31fc2f2baafcaccd81fa45',
    messagingSenderId: '215428045344',
    projectId: 'fireside-chat-5df62',
    databaseURL: 'https://fireside-chat-5df62-default-rtdb.firebaseio.com',
    storageBucket: 'fireside-chat-5df62.appspot.com',
    androidClientId: '215428045344-gqc1rhd6utdljt14i1lh959vre2bs4i5.apps.googleusercontent.com',
    iosClientId: '215428045344-trqkd28mokn42kmmvk4um4avgkp16til.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniexpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG8mdOJtAlgMx2mSD0peUq4qBUlMvj8h4',
    appId: '1:215428045344:web:eb65082f7d299ff281fa45',
    messagingSenderId: '215428045344',
    projectId: 'fireside-chat-5df62',
    authDomain: 'fireside-chat-5df62.firebaseapp.com',
    databaseURL: 'https://fireside-chat-5df62-default-rtdb.firebaseio.com',
    storageBucket: 'fireside-chat-5df62.appspot.com',
    measurementId: 'G-5CWSK2SSM3',
  );
}
